// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceMMO.Data;

#nullable disable

namespace SpaceMMO.Data.Migrations
{
    [DbContext(typeof(SpaceMmoDbContext))]
    [Migration("20260730021113_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpaceMMO.Data.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_email");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.Body", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<double>("RadiusKm")
                        .HasColumnType("double precision")
                        .HasColumnName("radius_km");

                    b.Property<string>("SecurityLevel")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("security_level");

                    b.Property<int>("StarSystemId")
                        .HasColumnType("integer")
                        .HasColumnName("star_system_id");

                    b.HasKey("Id")
                        .HasName("pk_bodies");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_bodies_key");

                    b.HasIndex("StarSystemId")
                        .HasDatabaseName("ix_bodies_star_system_id");

                    b.ToTable("bodies", null, t =>
                        {
                            t.HasCheckConstraint("ck_bodies_radius_positive", "radius_km > 0");
                        });
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.Bounty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<int?>("ClaimedByCharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("claimed_by_character_id");

                    b.Property<long?>("ClaimedByDeathRecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("claimed_by_death_record_id");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<int>("PosterCharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("poster_character_id");

                    b.Property<int>("TargetCharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("target_character_id");

                    b.HasKey("Id")
                        .HasName("pk_bounties");

                    b.HasIndex("PosterCharacterId")
                        .HasDatabaseName("ix_bounties_poster_character_id");

                    b.HasIndex("TargetCharacterId")
                        .HasDatabaseName("ix_bounties_target_character_id")
                        .HasFilter("claimed_at IS NULL");

                    b.ToTable("bounties", null, t =>
                        {
                            t.HasCheckConstraint("ck_bounties_amount_positive", "amount > 0");
                        });
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint")
                        .HasColumnName("balance");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("HomeBodyId")
                        .HasColumnType("integer")
                        .HasColumnName("home_body_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("race");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_characters_account_id");

                    b.HasIndex("HomeBodyId")
                        .HasDatabaseName("ix_characters_home_body_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_characters_name");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.CharacterFaucetDaily", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<DateOnly>("UtcDate")
                        .HasColumnType("date")
                        .HasColumnName("utc_date");

                    b.Property<long>("CreditsGranted")
                        .HasColumnType("bigint")
                        .HasColumnName("credits_granted");

                    b.HasKey("CharacterId", "UtcDate")
                        .HasName("pk_character_faucet_daily");

                    b.ToTable("character_faucet_daily", null, t =>
                        {
                            t.HasCheckConstraint("ck_character_faucet_daily_non_negative", "credits_granted >= 0");
                        });
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.CharacterQuest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("QuestDefId")
                        .HasColumnType("integer")
                        .HasColumnName("quest_def_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("state");

                    b.Property<int>("StepOrdinal")
                        .HasColumnType("integer")
                        .HasColumnName("step_ordinal");

                    b.Property<int>("StepProgress")
                        .HasColumnType("integer")
                        .HasColumnName("step_progress");

                    b.HasKey("Id")
                        .HasName("pk_character_quests");

                    b.HasIndex("QuestDefId")
                        .HasDatabaseName("ix_character_quests_quest_def_id");

                    b.HasIndex("CharacterId", "QuestDefId", "State")
                        .HasDatabaseName("ix_character_quests_character_id_quest_def_id_state");

                    b.ToTable("character_quests", null, t =>
                        {
                            t.HasCheckConstraint("ck_character_quests_progress_non_negative", "step_ordinal > 0 AND step_progress >= 0");
                        });
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.CharacterSkill", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    b.Property<long>("Xp")
                        .HasColumnType("bigint")
                        .HasColumnName("xp");

                    b.HasKey("CharacterId", "SkillId")
                        .HasName("pk_character_skills");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_character_skills_skill_id");

                    b.ToTable("character_skills", null, t =>
                        {
                            t.HasCheckConstraint("ck_character_skills_xp_non_negative", "xp >= 0");
                        });
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.DeathRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("BodyId")
                        .HasColumnType("integer")
                        .HasColumnName("body_id");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("cause");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<int?>("KillerCharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("killer_character_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<long>("ResolutionSeed")
                        .HasColumnType("bigint")
                        .HasColumnName("resolution_seed");

                    b.Property<int>("StarSystemId")
                        .HasColumnType("integer")
                        .HasColumnName("star_system_id");

                    b.HasKey("Id")
                        .HasName("pk_death_records");

                    b.HasIndex("KillerCharacterId")
                        .HasDatabaseName("ix_death_records_killer_character_id")
                        .HasFilter("killer_character_id IS NOT NULL");

                    b.HasIndex("CharacterId", "OccurredAt")
                        .HasDatabaseName("ix_death_records_character_id_occurred_at");

                    b.ToTable("death_records", (string)null);
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.IndustryJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<DateTimeOffset>("CompletesAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completes_at");

                    b.Property<long>("FeePaid")
                        .HasColumnType("bigint")
                        .HasColumnName("fee_paid");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<int>("Runs")
                        .HasColumnType("integer")
                        .HasColumnName("runs");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("state");

                    b.Property<int>("StationId")
                        .HasColumnType("integer")
                        .HasColumnName("station_id");

                    b.HasKey("Id")
                        .HasName("pk_industry_jobs");

                    b.HasIndex("CompletesAt")
                        .HasDatabaseName("ix_industry_jobs_completes_at")
                        .HasFilter("state = 'Running'");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_industry_jobs_recipe_id");

                    b.HasIndex("StationId")
                        .HasDatabaseName("ix_industry_jobs_station_id");

                    b.HasIndex("CharacterId", "State")
                        .HasDatabaseName("ix_industry_jobs_character_id_state");

                    b.ToTable("industry_jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_industry_jobs_runs_positive", "runs > 0");
                        });
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.InsurancePolicy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long>("InsuredValue")
                        .HasColumnType("bigint")
                        .HasColumnName("insured_value");

                    b.Property<long>("ItemInstanceId")
                        .HasColumnType("bigint")
                        .HasColumnName("item_instance_id");

                    b.Property<long?>("PayoutAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("payout_amount");

                    b.Property<long>("PremiumPaid")
                        .HasColumnType("bigint")
                        .HasColumnName("premium_paid");

                    b.Property<DateTimeOffset>("PurchasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchased_at");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("tier");

                    b.HasKey("Id")
                        .HasName("pk_insurance_policies");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_insurance_policies_character_id");

                    b.HasIndex("ItemInstanceId")
                        .IsUnique()
                        .HasDatabaseName("ix_insurance_policies_item_instance_id")
                        .HasFilter("claimed_at IS NULL");

                    b.ToTable("insurance_policies", null, t =>
                        {
                            t.HasCheckConstraint("ck_insurance_policies_insured_value_non_negative", "insured_value >= 0");

                            t.HasCheckConstraint("ck_insurance_policies_payout_below_insured_value", "payout_amount IS NULL OR payout_amount < insured_value");

                            t.HasCheckConstraint("ck_insurance_policies_premium_non_negative", "premium_paid >= 0");
                        });
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.Inventory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("CapacityM3")
                        .HasColumnType("double precision")
                        .HasColumnName("capacity_m3");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("kind");

                    b.Property<long?>("ShipItemInstanceId")
                        .HasColumnType("bigint")
                        .HasColumnName("ship_item_instance_id");

                    b.Property<int?>("StationId")
                        .HasColumnType("integer")
                        .HasColumnName("station_id");

                    b.HasKey("Id")
                        .HasName("pk_inventories");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_inventories_character_id");

                    b.HasIndex("ShipItemInstanceId")
                        .HasDatabaseName("ix_inventories_ship_item_instance_id");

                    b.HasIndex("StationId")
                        .HasDatabaseName("ix_inventories_station_id");

                    b.HasIndex("CharacterId", "StationId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_inventories_character_id_station_id_kind");

                    b.ToTable("inventories", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventories_capacity_non_negative", "capacity_m3 >= 0");
                        });
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.InventoryItem", b =>
                {
                    b.Property<long>("InventoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_id");

                    b.Property<int>("ItemDefId")
                        .HasColumnType("integer")
                        .HasColumnName("item_def_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("InventoryId", "ItemDefId")
                        .HasName("pk_inventory_items");

                    b.HasIndex("ItemDefId")
                        .HasDatabaseName("ix_inventory_items_item_def_id");

                    b.ToTable("inventory_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_items_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.ItemDef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("category");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<double>("VolumeM3")
                        .HasColumnType("double precision")
                        .HasColumnName("volume_m3");

                    b.HasKey("Id")
                        .HasName("pk_item_defs");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_item_defs_key");

                    b.ToTable("item_defs", null, t =>
                        {
                            t.HasCheckConstraint("ck_item_defs_volume_positive", "volume_m3 > 0");
                        });
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.ItemInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AcquisitionValue")
                        .HasColumnType("bigint")
                        .HasColumnName("acquisition_value");

                    b.Property<int>("Condition")
                        .HasColumnType("integer")
                        .HasColumnName("condition");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DestroyedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("destroyed_at");

                    b.Property<long?>("InventoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_id");

                    b.Property<int>("ItemDefId")
                        .HasColumnType("integer")
                        .HasColumnName("item_def_id");

                    b.HasKey("Id")
                        .HasName("pk_item_instances");

                    b.HasIndex("InventoryId")
                        .HasDatabaseName("ix_item_instances_inventory_id");

                    b.HasIndex("ItemDefId")
                        .HasDatabaseName("ix_item_instances_item_def_id");

                    b.ToTable("item_instances", null, t =>
                        {
                            t.HasCheckConstraint("ck_item_instances_acquisition_non_negative", "acquisition_value >= 0");

                            t.HasCheckConstraint("ck_item_instances_condition_in_range", "condition BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.LedgerEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DeltaCredits")
                        .HasColumnType("bigint")
                        .HasColumnName("delta_credits");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("reason");

                    b.Property<long?>("ReferenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("reference_id");

                    b.HasKey("Id")
                        .HasName("pk_ledger_entries");

                    b.HasIndex("CharacterId", "CreatedAt")
                        .HasDatabaseName("ix_ledger_entries_character_id_created_at");

                    b.HasIndex("Reason", "CreatedAt")
                        .HasDatabaseName("ix_ledger_entries_reason_created_at");

                    b.ToTable("ledger_entries", (string)null);
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.MarketOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<long>("EscrowedCredits")
                        .HasColumnType("bigint")
                        .HasColumnName("escrowed_credits");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("ItemDefId")
                        .HasColumnType("integer")
                        .HasColumnName("item_def_id");

                    b.Property<DateTimeOffset>("PlacedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("placed_at");

                    b.Property<long>("Price")
                        .HasColumnType("bigint")
                        .HasColumnName("price");

                    b.Property<int>("QuantityOriginal")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_original");

                    b.Property<int>("QuantityRemaining")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_remaining");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("reserved_quantity");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("side");

                    b.Property<int>("StarSystemId")
                        .HasColumnType("integer")
                        .HasColumnName("star_system_id");

                    b.Property<int>("StationId")
                        .HasColumnType("integer")
                        .HasColumnName("station_id");

                    b.HasKey("Id")
                        .HasName("pk_market_orders");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_market_orders_character_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_market_orders_expires_at")
                        .HasFilter("cancelled_at IS NULL");

                    b.HasIndex("ItemDefId")
                        .HasDatabaseName("ix_market_orders_item_def_id");

                    b.HasIndex("StationId", "ItemDefId", "Side", "Price")
                        .HasDatabaseName("ix_market_orders_station_id_item_def_id_side_price")
                        .HasFilter("quantity_remaining > 0 AND cancelled_at IS NULL");

                    b.ToTable("market_orders", null, t =>
                        {
                            t.HasCheckConstraint("ck_market_orders_escrow_matches_side", "(side = 'Buy' AND reserved_quantity = 0) OR (side = 'Sell' AND escrowed_credits = 0)");

                            t.HasCheckConstraint("ck_market_orders_escrow_non_negative", "escrowed_credits >= 0");

                            t.HasCheckConstraint("ck_market_orders_price_positive", "price > 0");

                            t.HasCheckConstraint("ck_market_orders_quantity_original_positive", "quantity_original > 0");

                            t.HasCheckConstraint("ck_market_orders_quantity_remaining_in_range", "quantity_remaining >= 0 AND quantity_remaining <= quantity_original");

                            t.HasCheckConstraint("ck_market_orders_reserved_non_negative", "reserved_quantity >= 0");
                        });
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.QuestDef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CareerKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("career_key");

                    b.Property<int?>("CooldownSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("cooldown_seconds");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int?>("PrerequisiteQuestDefId")
                        .HasColumnType("integer")
                        .HasColumnName("prerequisite_quest_def_id");

                    b.Property<long>("RewardCredits")
                        .HasColumnType("bigint")
                        .HasColumnName("reward_credits");

                    b.Property<int?>("RewardSkillId")
                        .HasColumnType("integer")
                        .HasColumnName("reward_skill_id");

                    b.Property<long>("RewardXp")
                        .HasColumnType("bigint")
                        .HasColumnName("reward_xp");

                    b.HasKey("Id")
                        .HasName("pk_quest_defs");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_quest_defs_key");

                    b.HasIndex("PrerequisiteQuestDefId")
                        .HasDatabaseName("ix_quest_defs_prerequisite_quest_def_id");

                    b.HasIndex("RewardSkillId")
                        .HasDatabaseName("ix_quest_defs_reward_skill_id");

                    b.ToTable("quest_defs", null, t =>
                        {
                            t.HasCheckConstraint("ck_quest_defs_cooldown_positive", "cooldown_seconds IS NULL OR cooldown_seconds > 0");

                            t.HasCheckConstraint("ck_quest_defs_reward_non_negative", "reward_credits >= 0");

                            t.HasCheckConstraint("ck_quest_defs_xp_non_negative", "reward_xp >= 0");
                        });
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.QuestStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("ObjectiveType")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("objective_type");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("QuestDefId")
                        .HasColumnType("integer")
                        .HasColumnName("quest_def_id");

                    b.Property<string>("TargetKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_key");

                    b.HasKey("Id")
                        .HasName("pk_quest_steps");

                    b.HasIndex("QuestDefId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_quest_steps_quest_def_id_ordinal");

                    b.ToTable("quest_steps", null, t =>
                        {
                            t.HasCheckConstraint("ck_quest_steps_ordinal_positive", "ordinal > 0");

                            t.HasCheckConstraint("ck_quest_steps_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JobSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("job_seconds");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<int>("OutputItemDefId")
                        .HasColumnType("integer")
                        .HasColumnName("output_item_def_id");

                    b.Property<int>("OutputQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("output_quantity");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("integer")
                        .HasColumnName("required_level");

                    b.Property<int?>("RequiredToolItemDefId")
                        .HasColumnType("integer")
                        .HasColumnName("required_tool_item_def_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    b.HasKey("Id")
                        .HasName("pk_recipes");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_recipes_key");

                    b.HasIndex("OutputItemDefId")
                        .HasDatabaseName("ix_recipes_output_item_def_id");

                    b.HasIndex("RequiredToolItemDefId")
                        .HasDatabaseName("ix_recipes_required_tool_item_def_id");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_recipes_skill_id");

                    b.ToTable("recipes", null, t =>
                        {
                            t.HasCheckConstraint("ck_recipes_job_seconds_positive", "job_seconds > 0");

                            t.HasCheckConstraint("ck_recipes_level_in_range", "required_level BETWEEN 1 AND 99");

                            t.HasCheckConstraint("ck_recipes_output_positive", "output_quantity > 0");
                        });
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.RecipeInput", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<int>("ItemDefId")
                        .HasColumnType("integer")
                        .HasColumnName("item_def_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("RecipeId", "ItemDefId")
                        .HasName("pk_recipe_inputs");

                    b.HasIndex("ItemDefId")
                        .HasDatabaseName("ix_recipe_inputs_item_def_id");

                    b.ToTable("recipe_inputs", null, t =>
                        {
                            t.HasCheckConstraint("ck_recipe_inputs_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.ResourceNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BodyId")
                        .HasColumnType("integer")
                        .HasColumnName("body_id");

                    b.Property<int>("ItemDefId")
                        .HasColumnType("integer")
                        .HasColumnName("item_def_id");

                    b.Property<int>("QuantityMax")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_max");

                    b.Property<int>("QuantityRemaining")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_remaining");

                    b.Property<DateTimeOffset?>("RespawnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("respawn_at");

                    b.Property<int>("StarSystemId")
                        .HasColumnType("integer")
                        .HasColumnName("star_system_id");

                    b.HasKey("Id")
                        .HasName("pk_resource_nodes");

                    b.HasIndex("ItemDefId")
                        .HasDatabaseName("ix_resource_nodes_item_def_id");

                    b.HasIndex("RespawnAt")
                        .HasDatabaseName("ix_resource_nodes_respawn_at");

                    b.HasIndex("StarSystemId")
                        .HasDatabaseName("ix_resource_nodes_star_system_id");

                    b.HasIndex("BodyId", "ItemDefId")
                        .HasDatabaseName("ix_resource_nodes_body_id_item_def_id");

                    b.ToTable("resource_nodes", null, t =>
                        {
                            t.HasCheckConstraint("ck_resource_nodes_max_positive", "quantity_max > 0");

                            t.HasCheckConstraint("ck_resource_nodes_remaining_in_range", "quantity_remaining >= 0 AND quantity_remaining <= quantity_max");
                        });
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("category");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_skills_key");

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.StarSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("GalaxyX")
                        .HasColumnType("bigint")
                        .HasColumnName("galaxy_x");

                    b.Property<long>("GalaxyY")
                        .HasColumnType("bigint")
                        .HasColumnName("galaxy_y");

                    b.Property<long>("GalaxyZ")
                        .HasColumnType("bigint")
                        .HasColumnName("galaxy_z");

                    b.Property<int>("GeneratorVersion")
                        .HasColumnType("integer")
                        .HasColumnName("generator_version");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("SecurityLevel")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("security_level");

                    b.Property<long>("Seed")
                        .HasColumnType("bigint")
                        .HasColumnName("seed");

                    b.HasKey("Id")
                        .HasName("pk_star_systems");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_star_systems_key");

                    b.HasIndex("GalaxyX", "GalaxyY", "GalaxyZ")
                        .HasDatabaseName("ix_star_systems_galaxy_x_galaxy_y_galaxy_z");

                    b.ToTable("star_systems", (string)null);
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BodyId")
                        .HasColumnType("integer")
                        .HasColumnName("body_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("StarSystemId")
                        .HasColumnType("integer")
                        .HasColumnName("star_system_id");

                    b.HasKey("Id")
                        .HasName("pk_stations");

                    b.HasIndex("BodyId")
                        .HasDatabaseName("ix_stations_body_id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_stations_key");

                    b.HasIndex("StarSystemId")
                        .HasDatabaseName("ix_stations_star_system_id");

                    b.ToTable("stations", (string)null);
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.Trade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BuyOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("buy_order_id");

                    b.Property<int>("BuyerCharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("buyer_character_id");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<int>("ItemDefId")
                        .HasColumnType("integer")
                        .HasColumnName("item_def_id");

                    b.Property<long>("Price")
                        .HasColumnType("bigint")
                        .HasColumnName("price");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<long>("SalesTax")
                        .HasColumnType("bigint")
                        .HasColumnName("sales_tax");

                    b.Property<long>("SellOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("sell_order_id");

                    b.Property<int>("SellerCharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("seller_character_id");

                    b.Property<int>("StarSystemId")
                        .HasColumnType("integer")
                        .HasColumnName("star_system_id");

                    b.Property<int>("StationId")
                        .HasColumnType("integer")
                        .HasColumnName("station_id");

                    b.HasKey("Id")
                        .HasName("pk_trades");

                    b.HasIndex("ItemDefId", "ExecutedAt")
                        .HasDatabaseName("ix_trades_item_def_id_executed_at");

                    b.HasIndex("StationId", "ExecutedAt")
                        .HasDatabaseName("ix_trades_station_id_executed_at");

                    b.ToTable("trades", null, t =>
                        {
                            t.HasCheckConstraint("ck_trades_price_positive", "price > 0");

                            t.HasCheckConstraint("ck_trades_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("ck_trades_sales_tax_non_negative", "sales_tax >= 0");
                        });
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.Body", b =>
                {
                    b.HasOne("SpaceMMO.Data.Entities.StarSystem", "StarSystem")
                        .WithMany("Bodies")
                        .HasForeignKey("StarSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bodies_star_systems_star_system_id");

                    b.Navigation("StarSystem");
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.Bounty", b =>
                {
                    b.HasOne("SpaceMMO.Data.Entities.Character", "TargetCharacter")
                        .WithMany()
                        .HasForeignKey("TargetCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bounties_characters_target_character_id");

                    b.Navigation("TargetCharacter");
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.Character", b =>
                {
                    b.HasOne("SpaceMMO.Data.Entities.Account", "Account")
                        .WithMany("Characters")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_characters_accounts_account_id");

                    b.HasOne("SpaceMMO.Data.Entities.Body", "HomeBody")
                        .WithMany()
                        .HasForeignKey("HomeBodyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_characters_bodies_home_body_id");

                    b.Navigation("Account");

                    b.Navigation("HomeBody");
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.CharacterFaucetDaily", b =>
                {
                    b.HasOne("SpaceMMO.Data.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_character_faucet_daily_characters_character_id");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.CharacterQuest", b =>
                {
                    b.HasOne("SpaceMMO.Data.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_character_quests_characters_character_id");

                    b.HasOne("SpaceMMO.Data.Entities.QuestDef", "QuestDef")
                        .WithMany()
                        .HasForeignKey("QuestDefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_character_quests_quest_defs_quest_def_id");

                    b.Navigation("Character");

                    b.Navigation("QuestDef");
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.CharacterSkill", b =>
                {
                    b.HasOne("SpaceMMO.Data.Entities.Character", "Character")
                        .WithMany("Skills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_character_skills_characters_character_id");

                    b.HasOne("SpaceMMO.Data.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_character_skills_skills_skill_id");

                    b.Navigation("Character");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.DeathRecord", b =>
                {
                    b.HasOne("SpaceMMO.Data.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_death_records_characters_character_id");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.IndustryJob", b =>
                {
                    b.HasOne("SpaceMMO.Data.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_industry_jobs_characters_character_id");

                    b.HasOne("SpaceMMO.Data.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_industry_jobs_recipes_recipe_id");

                    b.HasOne("SpaceMMO.Data.Entities.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_industry_jobs_stations_station_id");

                    b.Navigation("Character");

                    b.Navigation("Recipe");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.InsurancePolicy", b =>
                {
                    b.HasOne("SpaceMMO.Data.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_insurance_policies_characters_character_id");

                    b.HasOne("SpaceMMO.Data.Entities.ItemInstance", "ItemInstance")
                        .WithMany()
                        .HasForeignKey("ItemInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_insurance_policies_item_instances_item_instance_id");

                    b.Navigation("Character");

                    b.Navigation("ItemInstance");
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.Inventory", b =>
                {
                    b.HasOne("SpaceMMO.Data.Entities.Character", "Character")
                        .WithMany("Inventories")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventories_characters_character_id");

                    b.HasOne("SpaceMMO.Data.Entities.ItemInstance", "ShipItemInstance")
                        .WithMany()
                        .HasForeignKey("ShipItemInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventories_item_instances_ship_item_instance_id");

                    b.HasOne("SpaceMMO.Data.Entities.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventories_stations_station_id");

                    b.Navigation("Character");

                    b.Navigation("ShipItemInstance");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.InventoryItem", b =>
                {
                    b.HasOne("SpaceMMO.Data.Entities.Inventory", "Inventory")
                        .WithMany("StackedItems")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_items_inventories_inventory_id");

                    b.HasOne("SpaceMMO.Data.Entities.ItemDef", "ItemDef")
                        .WithMany()
                        .HasForeignKey("ItemDefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_items_item_defs_item_def_id");

                    b.Navigation("Inventory");

                    b.Navigation("ItemDef");
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.ItemInstance", b =>
                {
                    b.HasOne("SpaceMMO.Data.Entities.Inventory", "Inventory")
                        .WithMany("Instances")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_item_instances_inventories_inventory_id");

                    b.HasOne("SpaceMMO.Data.Entities.ItemDef", "ItemDef")
                        .WithMany()
                        .HasForeignKey("ItemDefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_item_instances_item_defs_item_def_id");

                    b.Navigation("Inventory");

                    b.Navigation("ItemDef");
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.LedgerEntry", b =>
                {
                    b.HasOne("SpaceMMO.Data.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_entries_characters_character_id");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.MarketOrder", b =>
                {
                    b.HasOne("SpaceMMO.Data.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_market_orders_characters_character_id");

                    b.HasOne("SpaceMMO.Data.Entities.ItemDef", "ItemDef")
                        .WithMany()
                        .HasForeignKey("ItemDefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_market_orders_item_defs_item_def_id");

                    b.HasOne("SpaceMMO.Data.Entities.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_market_orders_stations_station_id");

                    b.Navigation("Character");

                    b.Navigation("ItemDef");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.QuestDef", b =>
                {
                    b.HasOne("SpaceMMO.Data.Entities.QuestDef", "PrerequisiteQuestDef")
                        .WithMany()
                        .HasForeignKey("PrerequisiteQuestDefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_quest_defs_quest_defs_prerequisite_quest_def_id");

                    b.HasOne("SpaceMMO.Data.Entities.Skill", "RewardSkill")
                        .WithMany()
                        .HasForeignKey("RewardSkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_quest_defs_skills_reward_skill_id");

                    b.Navigation("PrerequisiteQuestDef");

                    b.Navigation("RewardSkill");
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.QuestStep", b =>
                {
                    b.HasOne("SpaceMMO.Data.Entities.QuestDef", "QuestDef")
                        .WithMany("Steps")
                        .HasForeignKey("QuestDefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quest_steps_quest_defs_quest_def_id");

                    b.Navigation("QuestDef");
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.Recipe", b =>
                {
                    b.HasOne("SpaceMMO.Data.Entities.ItemDef", "OutputItemDef")
                        .WithMany()
                        .HasForeignKey("OutputItemDefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recipes_item_defs_output_item_def_id");

                    b.HasOne("SpaceMMO.Data.Entities.ItemDef", "RequiredToolItemDef")
                        .WithMany()
                        .HasForeignKey("RequiredToolItemDefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recipes_item_defs_required_tool_item_def_id");

                    b.HasOne("SpaceMMO.Data.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recipes_skills_skill_id");

                    b.Navigation("OutputItemDef");

                    b.Navigation("RequiredToolItemDef");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.RecipeInput", b =>
                {
                    b.HasOne("SpaceMMO.Data.Entities.ItemDef", "ItemDef")
                        .WithMany()
                        .HasForeignKey("ItemDefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_inputs_item_defs_item_def_id");

                    b.HasOne("SpaceMMO.Data.Entities.Recipe", "Recipe")
                        .WithMany("Inputs")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_inputs_recipes_recipe_id");

                    b.Navigation("ItemDef");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.ResourceNode", b =>
                {
                    b.HasOne("SpaceMMO.Data.Entities.Body", "Body")
                        .WithMany()
                        .HasForeignKey("BodyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resource_nodes_bodies_body_id");

                    b.HasOne("SpaceMMO.Data.Entities.ItemDef", "ItemDef")
                        .WithMany()
                        .HasForeignKey("ItemDefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resource_nodes_item_defs_item_def_id");

                    b.HasOne("SpaceMMO.Data.Entities.StarSystem", "StarSystem")
                        .WithMany()
                        .HasForeignKey("StarSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resource_nodes_star_systems_star_system_id");

                    b.Navigation("Body");

                    b.Navigation("ItemDef");

                    b.Navigation("StarSystem");
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.Station", b =>
                {
                    b.HasOne("SpaceMMO.Data.Entities.Body", "Body")
                        .WithMany("Stations")
                        .HasForeignKey("BodyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_stations_bodies_body_id");

                    b.HasOne("SpaceMMO.Data.Entities.StarSystem", "StarSystem")
                        .WithMany("Stations")
                        .HasForeignKey("StarSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stations_star_systems_star_system_id");

                    b.Navigation("Body");

                    b.Navigation("StarSystem");
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.Trade", b =>
                {
                    b.HasOne("SpaceMMO.Data.Entities.ItemDef", "ItemDef")
                        .WithMany()
                        .HasForeignKey("ItemDefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trades_item_defs_item_def_id");

                    b.Navigation("ItemDef");
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.Account", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.Body", b =>
                {
                    b.Navigation("Stations");
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.Character", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.Inventory", b =>
                {
                    b.Navigation("Instances");

                    b.Navigation("StackedItems");
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.QuestDef", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.Recipe", b =>
                {
                    b.Navigation("Inputs");
                });

            modelBuilder.Entity("SpaceMMO.Data.Entities.StarSystem", b =>
                {
                    b.Navigation("Bodies");

                    b.Navigation("Stations");
                });
#pragma warning restore 612, 618
        }
    }
}
